const COURSELIST = [
  {
    id: 4367336,
    title:
      "【한글자막】 Python 부트캠프 : 100개의 프로젝트로 Python 개발 완전 정복",
    url: "/course/best-100-days-python/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 31334738,
        title: "Dr. Angela Yu",
        name: "Dr. Angela",
        display_name: "Dr. Angela Yu",
        job_title: "Developer and Lead Instructor",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/31334738_a13c_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/31334738_a13c_3.jpg",
        initials: "DY",
        url: "/user/4b4368a3-b5c8-4529-aa65-2056ec31f37e/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4367336_0573_7.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4367336_0573_7.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4367336_0573_7.jpg",
    published_title: "best-100-days-python",
    tracking_id: "rwLLYWLKS4yI0uHeviefig",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "전세계 10만명이 넘게 수강한 Python 수업! 데이터사이언스, 웹 개발, 크롤링, GUI 프로그래밍, 게임 등 Python을 통해 개발할 수 있는 모든 것을 다뤄보는 All-in-one 코스",
    num_subscribers: 9165,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_LA",
        title: "Español",
        english_title: "Spanish",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "ja_JP",
        title: "日本語",
        english_title: "Japanese",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pt_PT",
        title: "Português (Portugal)",
        english_title: "Portuguese (Portugal)",
      },
      {
        _class: "locale",
        locale: "ru_RU",
        title: "Русский",
        english_title: "Russian",
      },
      {
        _class: "locale",
        locale: "zh_CN",
        title: "中文(简体)",
        english_title: "Simplified Chinese (China)",
      },
    ],
    avg_rating: 4.7487683,
    avg_rating_recent: 4.744533,
    rating: 4.744533,
    num_reviews: 1588,
    is_wishlisted: false,
    num_published_lectures: 675,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4367336_0573_7.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4367336_0573_7.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4367336_0573_7.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4367336_0573_7.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "러시아어",
      "스페인어",
      "영어",
      "일본어",
      "중국어 간체",
      "포르투갈어",
      "프랑스어",
    ],
    created: "2021-10-26T08:35:15Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-12-18T05:40:37Z",
    objectives_summary: [
      "Python 기초 문법",
      "OOP(객체 지향 프로그래밍), Python 심화 문법(동적 타이핑, 리스트 컴프리헨션 등)",
      "데이터사이언스를 위한 Python 활용 및 핵심 라이브러리 사용법(Numpy, Pandas, Matplotlib, Seaborn, Plotly, Scikit-Learn 등)",
    ],
    is_recently_published: false,
    last_update_date: "2022-10-23",
    preview_url: "/course/4367336/preview/",
    learn_url: "/course/best-100-days-python/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 64.5시간",
    content_info_short: "64.5시간",
    bestseller_badge_content: {
      _class: "ds_course_badge",
      id: "c554516d14824efaa170258e7b33efc0",
      badge_text: "Bestseller",
      badge_family: "bestseller",
      context_info: {
        category: {
          id: 288,
          title: "개발",
          url: "/courses/development/",
          tracking_object_type: "cat",
        },
        subcategory: null,
        label: null,
      },
    },
    badges: [
      {
        _class: "ds_course_badge",
        id: "b4daddf0c2b04238988e55546c4008d8",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7380,
            display_name: "Python",
            title: "Python",
            topic_channel_url: "/topic/python/",
            url: "/topic/python/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 7380,
        display_name: "Python",
        title: "Python",
        topic_channel_url: "/topic/python/",
        url: "/topic/python/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4298905,
    title: "【한글자막】 React 완벽 가이드 with Redux, Next.js, TypeScript",
    url: "/course/best-react/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 31926668,
        title: "Academind by Maximilian Schwarzmüller",
        name: "Academind by Maximilian",
        display_name: "Academind by Maximilian Schwarzmüller",
        job_title: "Online Education",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
        initials: "AS",
        url: "/user/academind/",
      },
      {
        _class: "user",
        id: 13952972,
        title: "Maximilian Schwarzmüller",
        name: "Maximilian",
        display_name: "Maximilian Schwarzmüller",
        job_title: "AWS certified, Professional Web Developer and Instructor",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
        initials: "MS",
        url: "/user/maximilian-schwarzmuller/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4298905_17e3_2.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4298905_17e3_2.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4298905_17e3_2.jpg",
    published_title: "best-react",
    tracking_id: "pOTRdK-ORYCJt-hJWTqlnw",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "Javascript부터 웹 어플리케이션 배포까지, React와 프론트엔드 최신 기술을 가장 쉽고 확실하게 배우는 법",
    num_subscribers: 9787,
    caption_locales: [
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
    ],
    avg_rating: 4.7042804,
    avg_rating_recent: 4.7118096,
    rating: 4.7118096,
    num_reviews: 1554,
    is_wishlisted: false,
    num_published_lectures: 523,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4298905_17e3_2.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4298905_17e3_2.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4298905_17e3_2.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4298905_17e3_2.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["한국어"],
    created: "2021-09-14T15:49:57Z",
    instructional_level: "초급자 수준",
    instructional_level_simple: "초급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-10-25T17:25:44Z",
    objectives_summary: [
      "리액티브 웹 앱의 성능을 향상시키는 법",
      "JavaScript의 장점을 극대화하는 React 개발방법론",
      "React 심화 개념(useCallback, useMemo, useReducer etc)",
    ],
    is_recently_published: false,
    last_update_date: "2023-02-24",
    preview_url: "/course/4298905/preview/",
    learn_url: "/course/best-react/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 49시간",
    content_info_short: "49시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "7ca8676515964648badfbc36a782cb81",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 7450,
            display_name: "React JS",
            title: "React JS",
            topic_channel_url: "/topic/react/",
            url: "/topic/react/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 7450,
        display_name: "React JS",
        title: "React JS",
        topic_channel_url: "/topic/react/",
        url: "/topic/react/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4297574,
    title: "【한글자막】 The Web Developer 부트캠프 2023",
    url: "/course/the-web-developer-bootcamp-2021-korea/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 4466306,
        title: "Colt Steele",
        name: "Colt",
        display_name: "Colt Steele",
        job_title: "Developer and Bootcamp Instructor",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/4466306_6fd8_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/4466306_6fd8_3.jpg",
        initials: "CS",
        url: "/user/coltsteele/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4297574_42d1_4.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4297574_42d1_4.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4297574_42d1_4.jpg",
    published_title: "the-web-developer-bootcamp-2021-korea",
    tracking_id: "w4jZpEXPQmqndP2rT9u-LQ",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "전세계 25만명이 선택한 유데미 베스트셀러! HTML, CSS, JavaScript, Node.js 등을 활용한 13개 이상의 프로젝트로 확실하게 웹 개발 입문 완성",
    num_subscribers: 7174,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pl_PL",
        title: "Polski",
        english_title: "Polish",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
    ],
    avg_rating: 4.8093023,
    avg_rating_recent: 4.8074293,
    rating: 4.8074293,
    num_reviews: 1322,
    is_wishlisted: false,
    num_published_lectures: 613,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4297574_42d1_4.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4297574_42d1_4.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4297574_42d1_4.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4297574_42d1_4.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "독일어 [자동]",
      "스페인어 [자동]",
      "영어 [자동]",
      "이탈리아어 [자동]",
      "포르투갈어 [자동]",
      "폴란드어 [자동]",
      "프랑스어 [자동]",
    ],
    created: "2021-09-13T23:19:29Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-09-21T22:47:34Z",
    objectives_summary: [
      "웹 개발 최신 문법 (HTML5, CSS3, 모던 자바스크립트)",
      "Bootstrap 5, Semantic UI, Bulma 등 실무 CSS 프레임워크 사용법",
      "정적 HTML과 CSS로 포트폴리오 사이트 만들기",
    ],
    is_recently_published: false,
    last_update_date: "2023-05-05",
    preview_url: "/course/4297574/preview/",
    learn_url: "/course/the-web-developer-bootcamp-2021-korea/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 63.5시간",
    content_info_short: "63.5시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "cde375ef11d7492ba0380356ba397a46",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 8322,
            display_name: "웹 개발",
            title: "웹 개발",
            topic_channel_url: "/topic/web-development/",
            url: "/topic/web-development/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8322,
        display_name: "웹 개발",
        title: "웹 개발",
        topic_channel_url: "/topic/web-development/",
        url: "/topic/web-development/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 1341186,
    title: "retr0의 유니티 (Unity C#) 게임 프로그래밍 에센스",
    url: "/course/retr0-unity/",
    price: 88000,
    real_price: null,
    visible_instructors: [
      {
        _class: "user",
        id: 33341790,
        title: "retr0 by I_Jemin",
        name: "retr0",
        display_name: "retr0 by I_Jemin",
        job_title: "유니티 트레이너, 게임 프로그래머",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/33341790_6239_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/33341790_6239_3.jpg",
        initials: "RB",
        url: "/user/jemin-lee-2/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1341186_804d_15.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1341186_804d_15.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1341186_804d_15.jpg",
    published_title: "retr0-unity",
    tracking_id: "2MvzYWVeTy2hd0ddpxQjHQ",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline: "간결하고 탁월한 유니티 게임 프로그래밍 튜토리얼",
    num_subscribers: 2287,
    caption_locales: [],
    avg_rating: 4.85,
    avg_rating_recent: 4.7386556,
    rating: 4.7386556,
    num_reviews: 977,
    is_wishlisted: false,
    num_published_lectures: 169,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/1341186_804d_15.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1341186_804d_15.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1341186_804d_15.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/1341186_804d_15.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2017-09-04T09:57:45Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2017-11-06T18:58:04Z",
    objectives_summary: [
      "혼자서 유니티 게임을 완성할 수 있는 능력",
      "80% 이상의 유니티 에디터 사용법",
      "중급의 유니티 C# 클라이언트 프로그래밍",
    ],
    is_recently_published: false,
    last_update_date: "2020-06-13",
    preview_url: "/course/1341186/preview/",
    learn_url: "/course/retr0-unity/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 24시간",
    content_info_short: "24시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "37cfd5f1544d49d28e3c12a295d1da50",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 4904,
            display_name: "C#",
            title: "C#",
            topic_channel_url: "/topic/c-sharp/",
            url: "/topic/c-sharp/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 4904,
        display_name: "C#",
        title: "C#",
        topic_channel_url: "/topic/c-sharp/",
        url: "/topic/c-sharp/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4305113,
    title: "【한글자막】 JavaScript 알고리즘 & 자료구조 마스터클래스",
    url: "/course/best-javascript-data-structures/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 4466306,
        title: "Colt Steele",
        name: "Colt",
        display_name: "Colt Steele",
        job_title: "Developer and Bootcamp Instructor",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/4466306_6fd8_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/4466306_6fd8_3.jpg",
        initials: "CS",
        url: "/user/coltsteele/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4305113_68d5_4.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4305113_68d5_4.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4305113_68d5_4.jpg",
    published_title: "best-javascript-data-structures",
    tracking_id: "YF_-LK1-SxKN9KdE8zis4A",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "정렬, 리스트, 힙 스택을 포함한 12개의 알고리즘과 10개 이상 자료구조 학습으로 기술 면접 완벽하게 대비!",
    num_subscribers: 5099,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pl_PL",
        title: "Polski",
        english_title: "Polish",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
      {
        _class: "locale",
        locale: "ro_RO",
        title: "Română",
        english_title: "Romanian",
      },
      {
        _class: "locale",
        locale: "th_TH",
        title: "ภาษาไทย",
        english_title: "Thai",
      },
    ],
    avg_rating: 4.6975307,
    avg_rating_recent: 4.6971383,
    rating: 4.6971383,
    num_reviews: 677,
    is_wishlisted: false,
    num_published_lectures: 249,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4305113_68d5_4.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4305113_68d5_4.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4305113_68d5_4.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4305113_68d5_4.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "독일어 [자동]",
      "루마니아어 [자동]",
      "스페인어 [자동]",
      "영어 [자동]",
      "이탈리아어 [자동]",
      "인도네시아어 [자동]",
      "태국어 [자동]",
      "포르투갈어 [자동]",
      "폴란드어 [자동]",
      "프랑스어 [자동]",
    ],
    created: "2021-09-17T18:08:49Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-11-26T04:58:24Z",
    objectives_summary: [
      "Big O 표기법을 기반으로한 알고리즘 성능 평가법",
      "재귀(Recursion)",
      "정렬알고리즘(버블, 선택, 삽입, 병합, 퀵, 지수, 검색 등)",
    ],
    is_recently_published: false,
    last_update_date: "2022-01-12",
    preview_url: "/course/4305113/preview/",
    learn_url: "/course/best-javascript-data-structures/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 22시간",
    content_info_short: "22시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "864213fea8b04163b037b95e5b5032ea",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 4440,
            display_name: "Java 알고리즘",
            title: "Java 알고리즘",
            topic_channel_url: "/topic/java-algorithms/",
            url: "/topic/java-algorithms/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 4440,
        display_name: "Java 알고리즘",
        title: "Java 알고리즘",
        topic_channel_url: "/topic/java-algorithms/",
        url: "/topic/java-algorithms/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 2003154,
    title: "C++ 언매니지드 프로그래밍",
    url: "/course/cpp-unmanaged-programming-by-pocu/",
    price: 219000,
    real_price: null,
    visible_instructors: [
      {
        _class: "user",
        id: 51423906,
        title: "Pope Kim",
        name: "Pope",
        display_name: "Pope Kim",
        job_title: "CTO, Software Architect & Educator",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/51423906_336b.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/51423906_336b.jpg",
        initials: "PK",
        url: "/user/pope-kim/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/2003154_8191.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/2003154_8191.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/2003154_8191.jpg",
    published_title: "cpp-unmanaged-programming-by-pocu",
    tracking_id: "cEfDNRBMQn6XJDOZgUsDcg",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline: "실제 업계에서 쓰이는 C++ 프로그래밍의 기본기",
    num_subscribers: 1180,
    caption_locales: [
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
    ],
    avg_rating: 4.55,
    avg_rating_recent: 4.5720468,
    rating: 4.5720468,
    num_reviews: 633,
    is_wishlisted: false,
    num_published_lectures: 237,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/2003154_8191.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/2003154_8191.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/2003154_8191.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/2003154_8191.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["한국어"],
    created: "2018-11-02T05:07:06Z",
    instructional_level: "중급자 수준",
    instructional_level_simple: "중급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2018-12-18T18:54:16Z",
    objectives_summary: [
      "C++ 언어 사용법",
      "올바른 프로그래밍 습관",
      "C++ 언어가 내부적으로 어떻게 도는지에 대한 이해",
    ],
    is_recently_published: false,
    last_update_date: "2023-04-17",
    preview_url: "/course/2003154/preview/",
    learn_url: "/course/cpp-unmanaged-programming-by-pocu/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 25.5시간",
    content_info_short: "25.5시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "1209092100b7463cb9ffe0413a5c855a",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 4908,
            display_name: "C++",
            title: "C++",
            topic_channel_url: "/topic/c-plus-plus/",
            url: "/topic/c-plus-plus/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 4908,
        display_name: "C++",
        title: "C++",
        topic_channel_url: "/topic/c-plus-plus/",
        url: "/topic/c-plus-plus/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4482288,
    title: "【한글자막】 Docker & Kubernetes : 실전 가이드",
    url: "/course/docker-kubernetes-2022/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 31926668,
        title: "Academind by Maximilian Schwarzmüller",
        name: "Academind by Maximilian",
        display_name: "Academind by Maximilian Schwarzmüller",
        job_title: "Online Education",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
        initials: "AS",
        url: "/user/academind/",
      },
      {
        _class: "user",
        id: 13952972,
        title: "Maximilian Schwarzmüller",
        name: "Maximilian",
        display_name: "Maximilian Schwarzmüller",
        job_title: "AWS certified, Professional Web Developer and Instructor",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
        initials: "MS",
        url: "/user/maximilian-schwarzmuller/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4482288_58fb_3.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4482288_58fb_3.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4482288_58fb_3.jpg",
    published_title: "docker-kubernetes-2022",
    tracking_id: "1U2zx7uCSRmRXLwE783CHg",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "Docker, Docker Compose, 다중 컨테이너 프로젝트, Deployment 및 Kubernetes에 대한 모든 것을 기초부터 배워보세요!",
    num_subscribers: 4420,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
    ],
    avg_rating: 4.7395835,
    avg_rating_recent: 4.8011403,
    rating: 4.8011403,
    num_reviews: 555,
    is_wishlisted: false,
    num_published_lectures: 259,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4482288_58fb_3.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4482288_58fb_3.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4482288_58fb_3.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4482288_58fb_3.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "독일어 [자동]",
      "스페인어 [자동]",
      "영어",
      "이탈리아어 [자동]",
      "인도네시아어 [자동]",
      "포르투갈어 [자동]",
      "프랑스어 [자동]",
    ],
    created: "2022-01-07T17:09:11Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2022-03-05T08:42:48Z",
    objectives_summary: [
      "Docker와 Kubernetes가 무엇이며,  왜 사용해야 하는지를  배우게 됩니다.",
      "모든 시스템(macOS, Windows, Linux)에 Docker를 설치하고 사용하는 방법을 배웁니다.",
      "Docker로 이미지 및 컨테이너의 생성법과  사용법을 배웁니다.",
    ],
    is_recently_published: false,
    last_update_date: "2023-04-25",
    preview_url: "/course/4482288/preview/",
    learn_url: "/course/docker-kubernetes-2022/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 23.5시간",
    content_info_short: "23.5시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "3c5e17532d26481293e714d250f2bdc0",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 5470,
            display_name: "Docker",
            title: "Docker",
            topic_channel_url: "/topic/docker/",
            url: "/topic/docker/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5470,
        display_name: "Docker",
        title: "Docker",
        topic_channel_url: "/topic/docker/",
        url: "/topic/docker/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 1080152,
    title: "모던 리액트(React)와 리덕스(Redux)",
    url: "/course/react-redux-korean/",
    price: 23000,
    real_price: 99000,
    visible_instructors: [
      {
        _class: "user",
        id: 28991962,
        title: "Will Park",
        name: "Will",
        display_name: "Will Park",
        job_title: "Developer, Entrepreneur, Nomad",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/28991962_de15.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/28991962_de15.jpg",
        initials: "WP",
        url: "/user/will-park/",
      },
      {
        _class: "user",
        id: 34065328,
        title: "블로터 아카데미KO",
        name: "블로터",
        display_name: "블로터 아카데미KO",
        job_title: "테크 스쿨",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/34065328_9d96_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/34065328_9d96_2.jpg",
        initials: "K",
        url: "/user/bloter-2/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1080152_f76d.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/1080152_f76d.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/1080152_f76d.jpg",
    published_title: "react-redux-korean",
    tracking_id: "YWfvfdwpS9CZwgYD5RbD8g",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "NPM, Webpack, ES6 가 지원되는 앱개발 튜토리얼을 통해 리액트와 리덕스 마스터하세요!",
    num_subscribers: 2314,
    caption_locales: [],
    avg_rating: 4.65,
    avg_rating_recent: 4.6285744,
    rating: 4.6285744,
    num_reviews: 552,
    is_wishlisted: false,
    num_published_lectures: 151,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/1080152_f76d.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/1080152_f76d.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/1080152_f76d.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/1080152_f76d.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2017-01-17T19:34:56Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2017-08-24T01:02:03Z",
    objectives_summary: [
      "리액트와 리덕스를 가지고 멋진 싱글 페이지 어플리케이션 만듭니다",
      "리덕스 어플리케이션 구조화 뒤의 기본 개념 마스터하게 됩니다",
      "구성화 가능한 컴포넌트를 만드는 것의 장점을 이해하게 됩니다",
    ],
    is_recently_published: false,
    last_update_date: "2017-12-05",
    preview_url: "/course/1080152/preview/",
    learn_url: "/course/react-redux-korean/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 26.5시간",
    content_info_short: "26.5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 7450,
        display_name: "React JS",
        title: "React JS",
        topic_channel_url: "/topic/react/",
        url: "/topic/react/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4482284,
    title: "【한글자막】 100일 코딩 챌린지 - Web Development 부트캠프",
    url: "/course/100-2022-web-development/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 31926668,
        title: "Academind by Maximilian Schwarzmüller",
        name: "Academind by Maximilian",
        display_name: "Academind by Maximilian Schwarzmüller",
        job_title: "Online Education",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
        initials: "AS",
        url: "/user/academind/",
      },
      {
        _class: "user",
        id: 13952972,
        title: "Maximilian Schwarzmüller",
        name: "Maximilian",
        display_name: "Maximilian Schwarzmüller",
        job_title: "AWS certified, Professional Web Developer and Instructor",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
        initials: "MS",
        url: "/user/maximilian-schwarzmuller/",
      },
      {
        _class: "user",
        id: 30035496,
        title: "Manuel Lorenz",
        name: "Manuel",
        display_name: "Manuel Lorenz",
        job_title: "Professional Business Analyst and Instructor",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/30035496_b180_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/30035496_b180_2.jpg",
        initials: "ML",
        url: "/user/manuel-lorenz/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4482284_7f7d_5.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4482284_7f7d_5.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4482284_7f7d_5.jpg",
    published_title: "100-2022-web-development",
    tracking_id: "EzxsXgl_SNuUcnnzjcW0Rw",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      '100일 안에 여러분을 웹 개발자로 만들어 드리겠습니다. 웹 개발의 처음부터 끝까지 100일 안에 배워봅시다! "기본"에서 "고급"까지 모든 내용이 포함되어 있습니다!',
    num_subscribers: 3247,
    caption_locales: [
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
    ],
    avg_rating: 4.8,
    avg_rating_recent: 4.791986,
    rating: 4.791986,
    num_reviews: 535,
    is_wishlisted: false,
    num_published_lectures: 645,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4482284_7f7d_5.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4482284_7f7d_5.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4482284_7f7d_5.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4482284_7f7d_5.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["한국어", "영어"],
    created: "2022-01-07T17:08:13Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2022-03-19T04:49:42Z",
    objectives_summary: [
      "웹 작동 방식과 웹 개발자로 시작하는 방법",
      "100일 안에 웹 개발 배우기(선택 사항 - 다른 속도를 선택할 수도 있음)",
      '웹사이트, 웹 앱 그리고 웹 서비스 구축(이러한"things"이 무엇인지 이해)',
    ],
    is_recently_published: false,
    last_update_date: "2022-11-17",
    preview_url: "/course/4482284/preview/",
    learn_url: "/course/100-2022-web-development/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 79.5시간",
    content_info_short: "79.5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8322,
        display_name: "웹 개발",
        title: "웹 개발",
        topic_channel_url: "/topic/web-development/",
        url: "/topic/web-development/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 1034434,
    title: "누구나 쉽게 배우는 Git(깃) & Github(깃허브)",
    url: "/course/how_to_start_git_and_github/",
    price: 27000,
    real_price: 59000,
    visible_instructors: [
      {
        _class: "user",
        id: 21076916,
        title: "Ohsung Kwon",
        name: "Ohsung",
        display_name: "Ohsung Kwon",
        job_title: "흔한개발자",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/21076916_019f_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/21076916_019f_2.jpg",
        initials: "OK",
        url: "/user/ohsung-kwon/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1034434_5d7a_3.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1034434_5d7a_3.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1034434_5d7a_3.jpg",
    published_title: "how_to_start_git_and_github",
    tracking_id: "Jiadea9yQnmbtCgnHe6gew",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "Git(깃)의 기초와 Github(깃허브) 활용법을 3.5시간만에 정복해봅시다!",
    num_subscribers: 2939,
    caption_locales: [],
    avg_rating: 4.05,
    avg_rating_recent: 4.4893017,
    rating: 4.4893017,
    num_reviews: 478,
    is_wishlisted: false,
    num_published_lectures: 35,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/1034434_5d7a_3.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1034434_5d7a_3.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1034434_5d7a_3.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/1034434_5d7a_3.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2016-12-07T12:13:11Z",
    instructional_level: "초급자 수준",
    instructional_level_simple: "초급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2016-12-20T20:31:26Z",
    objectives_summary: [
      "GIT의 기본 사용법에 대해 배웁니다.",
      "GIT을 이용해 협업하는 방법을 배웁니다.",
      "Github를 통해 오픈 소스 프로젝트에 참여하는 방법을 배웁니다.",
    ],
    is_recently_published: false,
    last_update_date: "2016-12-22",
    preview_url: "/course/1034434/preview/",
    learn_url: "/course/how_to_start_git_and_github/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 3.5시간",
    content_info_short: "3.5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 5954,
        display_name: "Git",
        title: "Git",
        topic_channel_url: "/topic/git/",
        url: "/topic/git/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4234852,
    title:
      "【한글자막】 Typescript :기초부터 실전형 프로젝트까지 with React + NodeJS",
    url: "/course/best-typescript-21/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 13952972,
        title: "Maximilian Schwarzmüller",
        name: "Maximilian",
        display_name: "Maximilian Schwarzmüller",
        job_title: "AWS certified, Professional Web Developer and Instructor",
        image_50x50: "https://img-b.udemycdn.com/user/50x50/13952972_e853.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/13952972_e853.jpg",
        initials: "MS",
        url: "/user/maximilian-schwarzmuller/",
      },
      {
        _class: "user",
        id: 31926668,
        title: "Academind by Maximilian Schwarzmüller",
        name: "Academind by Maximilian",
        display_name: "Academind by Maximilian Schwarzmüller",
        job_title: "Online Education",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
        initials: "AS",
        url: "/user/academind/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-b.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-b.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4234852_7089_3.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4234852_7089_3.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4234852_7089_3.jpg",
    published_title: "best-typescript-21",
    tracking_id: "VVzec79uSoSp1qnnYE2qJg",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "Typescript의 개념과 컴파일러 작동 방식, ES6 문법, JavaScript를 Typescript에 통합, Webpack으로 개발 환경 설정, 실제 사례를 배웁니다",
    num_subscribers: 3933,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pl_PL",
        title: "Polski",
        english_title: "Polish",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
    ],
    avg_rating: 4.4242425,
    avg_rating_recent: 4.376954,
    rating: 4.376954,
    num_reviews: 446,
    is_wishlisted: false,
    num_published_lectures: 198,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4234852_7089_3.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4234852_7089_3.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4234852_7089_3.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4234852_7089_3.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "독일어 [자동]",
      "스페인어 [자동]",
      "영어 [자동]",
      "이탈리아어 [자동]",
      "인도네시아어 [자동]",
      "포르투갈어 [자동]",
      "폴란드어 [자동]",
      "프랑스어 [자동]",
    ],
    created: "2021-08-10T23:09:13Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-11-05T03:48:55Z",
    objectives_summary: [
      "Typescript를 사용해야 하는 이유",
      "Typescript 작동방식에 대한 깊이 있는 이해",
      "Typescript 기본/심화 문법을 나의 개발 프로젝트에 적용하는 법",
    ],
    is_recently_published: false,
    last_update_date: "2023-01-10",
    preview_url: "/course/4234852/preview/",
    learn_url: "/course/best-typescript-21/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 15시간",
    content_info_short: "15시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "073d62e5de674400bd5608e71a4da2bd",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 8124,
            display_name: "Typescript",
            title: "Typescript",
            topic_channel_url: "/topic/typescript/",
            url: "/topic/typescript/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8124,
        display_name: "Typescript",
        title: "Typescript",
        topic_channel_url: "/topic/typescript/",
        url: "/topic/typescript/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4253080,
    title: "클린코드 자바스크립트 (2023 업데이트)",
    url: "/course/clean-code-js/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 30239054,
        title: "Poco Jang",
        name: "Poco",
        display_name: "Poco Jang",
        job_title: "프론트엔드 엔지니어",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/30239054_ae73_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/30239054_ae73_2.jpg",
        initials: "PJ",
        url: "/user/devjang/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4253080_1e23.jpg",
    image_240x135: "https://img-c.udemycdn.com/course/240x135/4253080_1e23.jpg",
    is_practice_test_course: false,
    image_480x270: "https://img-c.udemycdn.com/course/480x270/4253080_1e23.jpg",
    published_title: "clean-code-js",
    tracking_id: "9f3UV4zORY63DKw9lcrO5g",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "자바스크립트를 위한 코드 스타일부터 습관 그리고 클린 코드에 대해 함께 고민해보고 그 이유에 대해 탐구하고 또 학습해보는 시간을 가집니다.",
    num_subscribers: 3674,
    caption_locales: [],
    avg_rating: 4.513889,
    avg_rating_recent: 4.5768666,
    rating: 4.5768666,
    num_reviews: 439,
    is_wishlisted: false,
    num_published_lectures: 73,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4253080_1e23.jpg",
    image_100x100: "https://img-c.udemycdn.com/course/100x100/4253080_1e23.jpg",
    image_304x171: "https://img-c.udemycdn.com/course/304x171/4253080_1e23.jpg",
    image_750x422: "https://img-c.udemycdn.com/course/750x422/4253080_1e23.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2021-08-20T04:47:50Z",
    instructional_level: "중급자 수준",
    instructional_level_simple: "중급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-09-28T01:42:27Z",
    objectives_summary: [
      "자바스크립트로 코드를 작성하는 방법에 대해 고민해봅니다.",
      "코드를 작성할 때 위험을 예방하고 관리합니다.",
      "JavaScript의 특성을 파악합니다.",
    ],
    is_recently_published: false,
    last_update_date: "2023-05-01",
    preview_url: "/course/4253080/preview/",
    learn_url: "/course/clean-code-js/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 10.5시간",
    content_info_short: "10.5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 6368,
        display_name: "JavaScript",
        title: "JavaScript",
        topic_channel_url: "/topic/javascript/",
        url: "/topic/javascript/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 2310014,
    title: "실무 프로그래밍 입문 (C#)",
    url: "/course/intro-to-programming-in-csharp-by-pocu/",
    price: 219000,
    real_price: null,
    visible_instructors: [
      {
        _class: "user",
        id: 51423906,
        title: "Pope Kim",
        name: "Pope",
        display_name: "Pope Kim",
        job_title: "CTO, Software Architect & Educator",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/51423906_336b.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/51423906_336b.jpg",
        initials: "PK",
        url: "/user/pope-kim/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/2310014_0f06_4.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/2310014_0f06_4.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/2310014_0f06_4.jpg",
    published_title: "intro-to-programming-in-csharp-by-pocu",
    tracking_id: "uQt7nXrsQ-WQ5_i3yleEwQ",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "본 과목은 사용의 편의성 및 직관성, 그리고 성능이라는 세마리 토끼를 다 잡은 매우 훌륭한 매니지드(managed) 언어인 C#을 사용하여 모든 프로그래밍 언어에 공통되는 프로그래밍 기초지식에 대해 배워봅니다.",
    num_subscribers: 816,
    caption_locales: [
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
    ],
    avg_rating: 4.85,
    avg_rating_recent: 4.84462,
    rating: 4.84462,
    num_reviews: 437,
    is_wishlisted: false,
    num_published_lectures: 256,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/2310014_0f06_4.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/2310014_0f06_4.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/2310014_0f06_4.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/2310014_0f06_4.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: ["한국어"],
    created: "2019-04-06T18:14:28Z",
    instructional_level: "초급자 수준",
    instructional_level_simple: "초급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2019-04-15T22:34:44Z",
    objectives_summary: [
      "프로그래밍 기초",
      "올바른 프로그래밍 습관",
      "C# 사용법",
    ],
    is_recently_published: false,
    last_update_date: "2021-05-16",
    preview_url: "/course/2310014/preview/",
    learn_url: "/course/intro-to-programming-in-csharp-by-pocu/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 32.5시간",
    content_info_short: "32.5시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "71b0589974dc47f9b25982c7649f778e",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 11944,
            display_name: "프로그래밍 기초",
            title: "프로그래밍 기초",
            topic_channel_url: "/topic/programming-fundamentals/",
            url: "/topic/programming-fundamentals/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 11944,
        display_name: "프로그래밍 기초",
        title: "프로그래밍 기초",
        topic_channel_url: "/topic/programming-fundamentals/",
        url: "/topic/programming-fundamentals/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 1895374,
    title:
      "파이썬 Python 3 입문 - 미국 실리콘밸리 스타일의 코드로 실전 앱 개발 준비하기",
    url: "/course/python-beginner-korean/",
    price: 23000,
    real_price: 99000,
    visible_instructors: [
      {
        _class: "user",
        id: 16554222,
        title: "酒井 潤 (Jun Sakai)",
        name: "酒井 潤",
        display_name: "酒井 潤 (Jun Sakai)",
        job_title:
          "アメリカ シリコンバレー現役エンジニア、個人投資家、東アジア競技大会 金メダリスト サッカー選手",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/16554222_7df0_9.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/16554222_7df0_9.jpg",
        initials: " (",
        url: "/user/jun-sakai/",
      },
      {
        _class: "user",
        id: 53858994,
        title: "Haesung Hwang (황혜성)",
        name: "Haesung",
        display_name: "Haesung Hwang (황혜성)",
        job_title: "Tri-lingual Interpreter",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/53858994_3c3d_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/53858994_3c3d_3.jpg",
        initials: "HH",
        url: "/user/haesung-hwang/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/1895374_4916_2.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/1895374_4916_2.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/1895374_4916_2.jpg",
    published_title: "python-beginner-korean",
    tracking_id: "84LyeZz2THiJ7uxjEAcLxQ",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "실리콘밸리의 소프트웨어 엔지니어가 Python 3 의 입문, 응용, 코드스타일을 전수합니다. 본강의에서는 최근 수요가 급증하고 있는 데이터 분석과 웹 스크래핑에도 쓰이고 있는 Python 의 기초를 다질수 있습니다",
    num_subscribers: 2306,
    caption_locales: [],
    avg_rating: 4.1,
    avg_rating_recent: 4.103287,
    rating: 4.103287,
    num_reviews: 426,
    is_wishlisted: false,
    num_published_lectures: 290,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/1895374_4916_2.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/1895374_4916_2.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/1895374_4916_2.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/1895374_4916_2.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2018-09-04T21:30:57Z",
    instructional_level: "초급자 수준",
    instructional_level_simple: "초급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2018-11-09T00:29:59Z",
    objectives_summary: [
      "Python 3 의 기본을 습득할 수 있습니다.",
      "응용편의 강의도 있으니 간단한 애플리케이션 개발에 필요한 스킬도 습득할 수 있습니다.",
      "Pythonic code 의 스타일을 익힐 수 있습니다.",
    ],
    is_recently_published: false,
    last_update_date: "2020-05-30",
    preview_url: "/course/1895374/preview/",
    learn_url: "/course/python-beginner-korean/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 28.5시간",
    content_info_short: "28.5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 7380,
        display_name: "Python",
        title: "Python",
        topic_channel_url: "/topic/python/",
        url: "/topic/python/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4191520,
    title: "☕ 블랙커피 Vanilla JS Lv1. 문벅스 카페 메뉴 앱 만들기",
    url: "/course/vanilla-js-lv1/",
    price: 48000,
    real_price: null,
    visible_instructors: [
      {
        _class: "user",
        id: 167212944,
        title: "Maker Jun",
        name: "Maker",
        display_name: "Maker Jun",
        job_title: "Makerjun",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/167212944_6495_2.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/167212944_6495_2.jpg",
        initials: "MJ",
        url: "/user/imdongjun-5/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4191520_162a_2.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4191520_162a_2.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4191520_162a_2.jpg",
    published_title: "vanilla-js-lv1",
    tracking_id: "nUsDv2SqRpai-PGrGb7Kbg",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline: "Vanilla Javascript로 만들어보는 상태관리가 가능한 카페 메뉴 앱",
    num_subscribers: 1791,
    caption_locales: [],
    avg_rating: 4.7352943,
    avg_rating_recent: 4.6970344,
    rating: 4.6970344,
    num_reviews: 412,
    is_wishlisted: false,
    num_published_lectures: 42,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4191520_162a_2.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4191520_162a_2.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4191520_162a_2.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4191520_162a_2.jpg",
    is_in_user_subscription: false,
    has_closed_caption: false,
    caption_languages: [],
    created: "2021-07-18T14:17:27Z",
    instructional_level: "초급자 수준",
    instructional_level_simple: "초급자",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2021-08-30T22:36:26Z",
    objectives_summary: [
      "자바스크립트를 통해 상태관리 가능한 애플리케이션 개발",
      "자바스크립트 이벤트 처리",
      "웹서버와의 비동기 통신",
    ],
    is_recently_published: false,
    last_update_date: "2021-10-19",
    preview_url: "/course/4191520/preview/",
    learn_url: "/course/vanilla-js-lv1/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 5시간",
    content_info_short: "5시간",
    bestseller_badge_content: null,
    badges: [],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 8322,
        display_name: "웹 개발",
        title: "웹 개발",
        topic_channel_url: "/topic/web-development/",
        url: "/topic/web-development/",
        tracking_object_type: "cl",
      },
    },
  },
  {
    id: 4482286,
    title: "【한글자막】 JavaScript 완벽 가이드 : 초급 + 고급 마스터 과정",
    url: "/course/javascript-zw/",
    price: 20000,
    real_price: 88000,
    visible_instructors: [
      {
        _class: "user",
        id: 31926668,
        title: "Academind by Maximilian Schwarzmüller",
        name: "Academind by Maximilian",
        display_name: "Academind by Maximilian Schwarzmüller",
        job_title: "Online Education",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
        initials: "AS",
        url: "/user/academind/",
      },
      {
        _class: "user",
        id: 13952972,
        title: "Maximilian Schwarzmüller",
        name: "Maximilian",
        display_name: "Maximilian Schwarzmüller",
        job_title: "AWS certified, Professional Web Developer and Instructor",
        image_50x50: "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
        initials: "MS",
        url: "/user/maximilian-schwarzmuller/",
      },
      {
        _class: "user",
        id: 169413114,
        title: "웅진씽크빅 글로벌",
        name: "웅진씽크빅",
        display_name: "웅진씽크빅 글로벌",
        job_title:
          "대한민국 교육문화를 이끌어 온 웅진씽크빅(Woongjin Thinkbig)",
        image_50x50:
          "https://img-c.udemycdn.com/user/50x50/169413114_7bf2_3.jpg",
        image_100x100:
          "https://img-c.udemycdn.com/user/100x100/169413114_7bf2_3.jpg",
        initials: "",
        url: "/user/ellie-yang-10/",
      },
    ],
    image_125_H: "https://img-c.udemycdn.com/course/125_H/4482286_943e_4.jpg",
    image_240x135:
      "https://img-c.udemycdn.com/course/240x135/4482286_943e_4.jpg",
    is_practice_test_course: false,
    image_480x270:
      "https://img-c.udemycdn.com/course/480x270/4482286_943e_4.jpg",
    published_title: "javascript-zw",
    tracking_id: "8tvrUPobRyet2-BkY7953g",
    locale: {
      _class: "locale",
      locale: "ko_KR",
      title: "한국어",
      english_title: "Korean",
      simple_english_title: "Korean",
    },
    headline:
      "기초부터 시작하여 JS 전문가 수준까지 담은 최신 JavaScript 강의! 한 강의로 해결하는 JavaScript 웹 개발 완벽 가이드.",
    num_subscribers: 2627,
    caption_locales: [
      {
        _class: "locale",
        locale: "de_DE",
        title: "Deutsch",
        english_title: "German",
      },
      {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
      },
      {
        _class: "locale",
        locale: "es_ES",
        title: "Español (España)",
        english_title: "Spanish (Spain)",
      },
      {
        _class: "locale",
        locale: "fr_FR",
        title: "Français (France)",
        english_title: "French (France)",
      },
      {
        _class: "locale",
        locale: "id_ID",
        title: "Bahasa Indonesia",
        english_title: "Indonesian",
      },
      {
        _class: "locale",
        locale: "it_IT",
        title: "Italiano",
        english_title: "Italian",
      },
      {
        _class: "locale",
        locale: "ko_KR",
        title: "한국어",
        english_title: "Korean",
      },
      {
        _class: "locale",
        locale: "pt_BR",
        title: "Português (Brasil)",
        english_title: "Portuguese (Brazil)",
      },
    ],
    avg_rating: 4.7362638,
    avg_rating_recent: 4.7361,
    rating: 4.7361,
    num_reviews: 341,
    is_wishlisted: false,
    num_published_lectures: 617,
    num_published_practice_tests: 0,
    image_50x50: "https://img-c.udemycdn.com/course/50x50/4482286_943e_4.jpg",
    image_100x100:
      "https://img-c.udemycdn.com/course/100x100/4482286_943e_4.jpg",
    image_304x171:
      "https://img-c.udemycdn.com/course/304x171/4482286_943e_4.jpg",
    image_750x422:
      "https://img-c.udemycdn.com/course/750x422/4482286_943e_4.jpg",
    is_in_user_subscription: false,
    has_closed_caption: true,
    caption_languages: [
      "한국어",
      "독일어 [자동]",
      "스페인어 [자동]",
      "영어",
      "이탈리아어 [자동]",
      "인도네시아어 [자동]",
      "포르투갈어 [자동]",
      "프랑스어 [자동]",
    ],
    created: "2022-01-07T17:09:02Z",
    instructional_level: "모든 수준",
    instructional_level_simple: "모든 수준",
    content_length_practice_test_questions: 0,
    is_user_subscribed: false,
    buyable_object_type: "course",
    published_time: "2022-05-15T09:06:10Z",
    objectives_summary: [
      "처음부터 시작하는 JavaScript - 초급부터 고급까지",
      "최신 JavaScript 개발에서 알아야 할 모든 핵심 기능과 개념",
      "JavaScript 전문가가 되고 JavaScript 관련 직무에 지원하는 데 필요한 모든 것",
    ],
    is_recently_published: false,
    last_update_date: "2022-09-25",
    preview_url: "/course/4482286/preview/",
    learn_url: "/course/javascript-zw/learn/",
    is_in_personal_plan_collection: false,
    is_in_premium: false,
    has_508_closed_captions: false,
    is_coding_exercises_badge_eligible: false,
    predictive_score: null,
    relevancy_score: null,
    input_features: null,
    lecture_search_result: null,
    curriculum_lectures: [],
    order_in_results: null,
    curriculum_items: [],
    instructor_name: null,
    content_info: "총 52시간",
    content_info_short: "52시간",
    bestseller_badge_content: null,
    badges: [
      {
        _class: "ds_course_badge",
        id: "3651380575244b2ba92d2341b44a1308",
        badge_text: "Bestseller",
        badge_family: "bestseller",
        context_info: {
          category: {
            id: 288,
            title: "개발",
            url: "/courses/development/",
            tracking_object_type: "cat",
          },
          subcategory: null,
          label: {
            id: 6368,
            display_name: "JavaScript",
            title: "JavaScript",
            topic_channel_url: "/topic/javascript/",
            url: "/topic/javascript/",
            tracking_object_type: "cl",
          },
        },
      },
    ],
    free_course_subscribe_url: null,
    context_info: {
      category: {
        id: 288,
        title: "개발",
        url: "/courses/development/",
        tracking_object_type: "cat",
      },
      subcategory: null,
      label: {
        id: 6368,
        display_name: "JavaScript",
        title: "JavaScript",
        topic_channel_url: "/topic/javascript/",
        url: "/topic/javascript/",
        tracking_object_type: "cl",
      },
    },
  },
];
export default COURSELIST;
